==== Provisioning Physical Servers

Physical servers can be provisioned using Lenovo XClarity Administrator (LXCA) configuration patterns. Configuration patterns can be thought of as templates that describe the configuration of servers. The Lenovo Physical Infrastructure Provider discovers configuration patterns that are defined on the LXCA instance that is associated with the provider. A pattern can then be applied to a single or multiple physical servers. _Note:_ Configuration patterns can only be assigned to servers that do not already have a pattern assigned to them.

===== Provisioning a Single Server

include::navigate_to_physical_servers_page.adoc[]
. Click on the server you wish to provision. The *Physical Server* page for the server should load.
include::press-lifecycle-provision-server-button.adoc[]

===== Provisioning Multiple Servers

include::navigate_to_physical_servers_page.adoc[]
. Select the checkboxes of the servers you wish to provision.
include::press-lifecycle-provision-server-button.adoc[]
