=== Performing physical-infrastructure provider actions

You can use the REST API to perform actions on a physical-infrastructure provider, such as creating, modifying and deleting.

*Note:* To perform actions on physical-infrastructure providers, you must create a basic authentication using your preferred tool or library, and use the user name and password for the CloudForms instance when using the REST API.

===== Creating a Lenovo physical-infrastructure provider

To create a Lenovo physical-infrastructure provider, send a POST request using the following request URL and JSON request body.
----------------------------------------------
POST /api/providers
----------------------------------------------

Request body:
--------------------------------------------------------------
{
   "action": "create",  
   "credentials": {
      "password": "<PASSWORD>",
      "userid": "<USERNAME>" 
   }, 
   "hostname": "<LENOVO XCLARITY ADMINISTRATOR ADDRESS>",
   "name": "<NAME>", 
   "port": "<THE SERVICE PORT>", 
   "type": "ManageIQ::Providers::Lenovo::PhysicalInfraManager"
}
--------------------------------------------------------------

===== Modifying properties for a Lenovo physical-infrastructure provider 

To modify properties of a Lenovo physical-infrastructure provider, send a POST request using the following request URL and JSON request body.
----------------------------------------------
POST /api/providers
----------------------------------------------

Request body:
------------------------------------------------------------
{
   "action":"edit",
   "credentials": { 
      "password":"<new_passowrd>",
      "userid":"<new_user_name>" 
   }, 
   "hostname":"<New_Lenovo_XClarity_Administrator_address>",
   "name":"<new_provider_name>", 
   "port":"<new_service_port>"
}
------------------------------------------------------------

===== Refreshing information about all providers

To refresh information about all providers, send a POST request using the following request URL and JSON request body.
----------------------------------------------
POST /api/providers
----------------------------------------------

Request body:
---------------------
{
   "action":"refresh"
}
---------------------

===== Deleting a physical-infrastructure provider

To delete a specific provider:

* Send a DELETE request using the following request URL.
+
--------------------------------------------------------------
DELETE /api/providers/<provider_ID>
--------------------------------------------------------------
* Send a POST request using the following request URL and JSON request body.
+
------------------------------------------------------------
POST /api/providers/<provider_ID>
------------------------------------------------------------
+
Request body:
+
--------------------
{
   "action":"delete"
}
--------------------

===== Performing an action on multiple physical-infrastructure providers

To perform an action on more than one physical-infrastructure providers, send a POST request using the following request URL and JSON request body.
----------------------------------------------
POST /api/providers
----------------------------------------------

Request body:
-----------------------------
{
   "action":"<action>",  
   "resources": [{
      "href":"<provider_ID>"
   }, 
   {
      "href":"<provider_ID>"
   }]
}
-----------------------------
