=== Performing physical server actions

You can use the REST API to perform management tasks on a physical server, such as powering on an off, restarting, and changing the location-LED state.

*Note:* To perform actions on physical servers, you must create a basic authentication using your preferred tool or library, and enter your user name and password to access the CloudForms REST API.

===== Powering on a physical server
To power on a specific physical server, send a POST request using the following request URL and JSON request body.
----------------------------------------------------------------
POST <CloudForms_address>:<port>/api/physical_servers<server_ID>
----------------------------------------------------------------

Request body:
----------------------
{
   "action":"power_on"
}
----------------------

===== Powering off a physical server
To shut down the operating system and power off a specific physical server, send a POST request using the following request URL and JSON request body.
----------------------------------------------------------------
POST <CloudForms_address>:<port>/api/physical_servers<server_ID>
----------------------------------------------------------------

Request body:
-----------------------
{
   "action":"power_off"
}
-----------------------

===== Immediately powering off a physical server
To immediately power off a specific physical server, send a POST request using the following request URL and JSON request body.
----------------------------------------------------------------
POST <CloudForms_address>:<port>/api/physical_servers<server_ID>
----------------------------------------------------------------

Request body:
---------------------------
{
   "action":"power_off_now"
}
---------------------------

===== Restarting a physical server 
To shut down the operating system and restart a specific physical server, send a POST request using the following request URL and JSON request body.
----------------------------------------------------------------
POST <CloudForms_address>:<port>/api/physical_servers<server_ID>
----------------------------------------------------------------

Request body:
---------------------
{
   "action":"restart"
}
---------------------

===== Immediately restarting a physical server 
To immediately restart a specific physical server, send a POST request using the following request URL and JSON request body.
----------------------------------------------------------------
POST <CloudForms_address>:<port>/api/physical_servers<server_ID>
----------------------------------------------------------------

Request body:
-------------------------
{
   "action":"restart_now"
}
-------------------------

===== Changing the location LED state on a physical server to blinking
To change the location-LED state to blinking on a specific server, send a POST request using the following request URL and JSON request body.
----------------------------------------------------------------
POST <CloudForms_address>:<port>/api/physical_servers<server_ID>
----------------------------------------------------------------

Request body:
--------------------------
{
   "action":"blink_loc_led"
}
--------------------------

===== Performing an action on multiple physical servers 
To perform an action on more than one physical severs, send a POST request using the following request URL and JSON request body.
-----------------------------------------------------
POST <CloudForms_address>:<port>/api/physical_servers
-----------------------------------------------------

Request body:
-----------------------------
{
   "action":"<action>",
   "resources": [{
      "href":"<server_ID>"
   }, 
   {
      "href":"<server_ID>"
   }]
}
-----------------------------
