=== Retrieving Physical Server Details

To retrieve information for all physical servers, use the following request URL:
-----------------------------------------------------
GET <CloudForms_address>:<port>/api/physical_servers
-----------------------------------------------------

A JSON response with the following keys is returned.
------------------------------------------------------
actions (list of actions that can be used)
count (count of the physical servers)
name (URI name)
pages (count of pages)
resource (list of URLs of the each physical servers) 
subcount (count of the physical servers returned) 
------------------------------------------------------

*Examples*

* To retrieve all information about the physical servers, use the *?expand=resources* query parameter, for example:
+
--------------------------------------------------------
GET localhost:3000/api/physical_servers?expand=resources
--------------------------------------------------------
* To retrieve a specific information about the physical servers (such as name and ID), use the *?expand=resources&attributes=<attribute_list>* query parameters, for example:
+
---------------------------------------------------------------------------
GET localhost:3000/api/physical_servers?expand=resources&attributes=id,name
---------------------------------------------------------------------------
* To retrieve specific information about the physical servers (such as firmware, networks, guest devices, and asset details), use the *?expand=resources&attributes=<attribute_list>* query parameters, for example: 
+
-----------------------------------------------------------------------------------
GET localhost:3000/api/physical_servers?expand=resources&attributes= hardware.firmwares,hardware.networks,hardware.guest_devices,hardware.assets_details
-----------------------------------------------------------------------------------

* To retrieve information about only a specific physical server, use the *?expand=resources&filter[]=name=<server_name>* query attributes on all physical-server resources, for example:
+
------------------------------------------------------------------------------------------
GET localhost:3000/api/physical_servers?expand=resources&filter[]=name=Server1-20127X5462
------------------------------------------------------------------------------------------
