=== Retrieving Physical Server Details

To retrieve information for all physical servers, use the following request URL:
-----------------------------------------------------
GET /api/physical_servers
-----------------------------------------------------

A JSON response with the following keys is returned.
------------------------------------------------------
actions (list of actions that can be used)
count (number of physical servers)
name (URI name)
pages (number of pages)
resource (list of URLs for each physical server) 
subcount (number of physical servers that were returned) 
------------------------------------------------------

*Examples*

* To retrieve all information about the physical servers, use the *?expand=resources* query parameter, for example:
+
--------------------------------------------------------
GET /api/physical_servers?expand=resources
--------------------------------------------------------
* To retrieve specific information about the physical servers (such as name and ID), use the *?expand=resources&attributes=<attribute_list>* query parameters, for example:
+
---------------------------------------------------------------------------
GET /api/physical_servers?expand=resources&attributes=id,name
---------------------------------------------------------------------------
* To retrieve information such as firmware, networks, guest devices, and asset details associated with physical servers, use the *?expand=resources&attributes=<attribute_list>* query parameters, for example: 
+
-----------------------------------------------------------------------------------
GET /api/physical_servers?expand=resources&attributes=hardware.firmwares,hardware.networks,hardware.guest_devices,hardware.assets_details
-----------------------------------------------------------------------------------
* To retrieve information such as network adapters and storage adapters in physical servers, use the *?expand=resources&attributes=<attribute_list>* query parameters, for example: 
+
-----------------------------------------------------------------------------------
GET /api/physical_servers?expand=resources&attributes=guest_devices.with_ethernet_type,guest_devices.with_storage_type
-----------------------------------------------------------------------------------
* To retrieve information such as switches connected to physical servers, use the *?expand=resources&attributes=<attribute_list>* query parameters, for example: 
+
-----------------------------------------------------------------------------------
GET /api/physical_servers?expand=resources&attributes=physical_switches
-----------------------------------------------------------------------------------
* To retrieve information about only a specific physical server, use the *?expand=resources&filter[]=name=<server_name>* query attributes on all physical-server resources, for example:
+
------------------------------------------------------------------------------------------
GET /api/physical_servers?expand=resources&filter[]=name=Server1-20127X5462
------------------------------------------------------------------------------------------
