=== Retrieving Physical Chassis Details

To retrieve information for all physical chassis, use the following request URL:
-----------------------------------------------------
GET /api/physical_chassis
-----------------------------------------------------

A JSON response with the following keys is returned.
------------------------------------------------------
actions (list of actions that can be used)
count (number of physical chassis)
name (URI name)
pages (number of pages)
resources (list of URLs for each physical chassis) 
subcount (number of physical chassis that were returned) 
------------------------------------------------------

*Examples*

* To retrieve all information about the physical chassis, use the *?expand=resources* query parameter, for example:
+
--------------------------------------------------------
GET /api/physical_chassis?expand=resources
--------------------------------------------------------
* To retrieve specific information about the physical chassis (such as name and ID), use the *?expand=resources&attributes=<attribute_list>* query parameters, for example:
+
---------------------------------------------------------------------------
GET /api/physical_chassis?expand=resources&attributes=id,name
---------------------------------------------------------------------------
* To retrieve information such as the switches, storage systems, and servers in a chassis, use the *?expand=resources&attributes=<attribute_list>* query parameters, for example:
+
---------------------------------------------------------------------------
GET /api/physical_chassis?expand=resources&attributes=physical_servers,physical_storages,hardware.connected_physical_switches
---------------------------------------------------------------------------
* To retrieve information about only a specific physical chassis, use the *?expand=resources&filter[]=name=<chassis_name>* query attributes on all physical chassis resources, for example:
+
------------------------------------------------------------------------------------------
GET /api/physical_chassis?expand=resources&filter[]=name=SN%23Y034BG16E060
------------------------------------------------------------------------------------------
