=== Retrieving Physical Storage Details

To retrieve information for all physical storage systems, use the following request URL:
-----------------------------------------------------
GET /api/physical_storages
-----------------------------------------------------

A JSON response with the following keys is returned.
------------------------------------------------------
actions (list of actions that can be used)
count (number of physical storage systems)
name (URI name)
pages (number of pages)
resources (list of URLs for each physical storage system) 
subcount (number of physical storage systems that were returned) 
------------------------------------------------------

*Examples*

* To retrieve all information about the physical storage systems, use the *?expand=resources* query parameter, for example:
+
--------------------------------------------------------
GET /api/physical_storages?expand=resources
--------------------------------------------------------
* To retrieve specific information about the physical storage systems (such as name and ID), use the *?expand=resources&attributes=<attribute_list>* query parameters, for example:
+
---------------------------------------------------------------------------
GET /api/physical_storages?expand=resources&attributes=id,name
---------------------------------------------------------------------------
* To retrieve information such as canisters and physical disks associated with physical storage systems, use the *?expand=resources&attributes=<attribute_list>* query parameters, for example:
+
---------------------------------------------------------------------------
GET /api/physical_storages?expand=resources&attributes=canisters,physical_disks
---------------------------------------------------------------------------
* To retrieve information about only a specific physical storage system, use the *?expand=resources&filter[]=name=<storage_name>* query attributes on all physical storage resources, for example:
+
------------------------------------------------------------------------------------------
GET /api/physical_storages?expand=resources&filter[]=name=SeagateV1-S3200-DM
------------------------------------------------------------------------------------------
