=== Get a Provider by ID

. Log in to CloudForms Management Engine API as a user who has permission to access the API. The default user is admin, password smartvm.

. Use the following url structure for access the api **"<CLOUDFORMS ADDRESS>:<PORT>/api/" (ex. localhost:3000/api/)**.

. Use the following request for get a provider by ID. **(ex.localhost:3000/api/providers/<ID NUMBER>)**.

. It’s return a JSON with the following keys:

    href;
    id;
    name;
    created_on;
    updated_on;
    guid;
    zone_id;
    type;
    last_refresh_date;
    tenant_id;
    enabled;
    options;
    actions.

. If you wish get a custom data information, as name and id or an other attribute you need use the following query: **?attributes=id,name (ex. localhost:3000/api/providers/<ID NUMBER>?attributes=id,name)**.

. If you wish get a custom data information as port, hostname and ipaddress, you must use the following query for add that new attributes: **?attributes=port,hostname,ipaddress(ex. localhost:3000/api/providers/<ID NUMBER>?attributes=port,hostname,ipaddress).**