=== Retrieving Provider Details

To retrieve information for all providers, use the following request URL:
---------------------------------------------
GET /api/providers
---------------------------------------------

A JSON response with the following keys is returned.
-------------------------------------------------
actions (list of actions that can be used)
count (total number of providers) 
name (URI name)
pages (count of pages)
resource (list of URLs for each provider that is managed by CloudForms) 
subcount (number of providers returned) 
-------------------------------------------------

*Examples*

* To retrieve all information about the providers, use the *?expand=resources* query parameter, for example:
+
-------------------------------------------------
GET /api/providers?expand=resources
-------------------------------------------------
* To retrieve a specific information about the providers (such as name and ID), use the *?expand=resources&attributes=<attribute_list>* query parameters, for example:
+
---------------------------------------------------------------------
GET /api/providers?expand=resources&attributes=id,name
---------------------------------------------------------------------
* To retrieve additional information about the providers (such as port, hostname, and IP address), use the *?expand=resources&attributes=<attribute_list>* query parameters, for example:
+
------------------------------------------------------------------------------------
GET /api/providers?expand=resources&attributes=port,hostname,ipaddress
------------------------------------------------------------------------------------
* To retrieve information about only Lenovo physical-infrastructure providers, use the *?expand=resources&filter[]=type=<provider_type>* attribute against all provider resources, for example:
+
-----------------------------------------------------------------------------------------------------------------
GET /api/providers?expand=resources&filter[]=type=ManageIQ::Providers::Lenovo::PhysicalInfraManager
-----------------------------------------------------------------------------------------------------------------
