=== Retrieving Physical Server Details by ID

To retrieve information for a specific physical server, use the following request URL:
----------------------------------------------------------------
GET /api/physical_servers/<server_ID>
----------------------------------------------------------------

A JSON response with the following keys is returned.
----------------------
actions
created_at
ems_id
ems_ref
field_replaceable_unit
health_state
hostname
href
location_led_state
machine_type
manufacturer
model
name
power_state
product_name
serial_number
type
uid_ems
updated_at
vendor
----------------------

*Examples*

 
* To retrieve specific information about a specific physical server (such as name and ID), use the *?expand=resources&attributes=<attribute_list>* query parameters, for example:
+
---------------------------------------------------------------------------------------
GET /api/physical_servers/<server_ID>?expand=resources&attributes=id,name
---------------------------------------------------------------------------------------
* To retrieve information such as firmware, networks, guest devices, and asset details for a specific server, use the *?expand=resources&attributes=<attribute_list>* query parameters, for example:
+
-----------------------------------------------------------------------------------------------
GET /api/physical_servers/<server_ID>?expand=resources
&attributes=hardware.firmwares,hardware.networks,hardware.guest_devices,hardware.assets_details
-----------------------------------------------------------------------------------------------
* To retrieve information such as switches connected to a specific server, use the *?expand=resources&attributes=<attribute_list>* query parameters, for example: 
+
-----------------------------------------------------------------------------------
GET /api/physical_servers/<server_ID>?expand=resources&attributes=physical_switches
-----------------------------------------------------------------------------------
* To retrieve information such as network adapters and storage adapters in a specific physical server, use the *?expand=resources&attributes=<attribute_list>* query parameters, for example:
+
-----------------------------------------------------------------------------------------------
GET /api/physical_servers/<server_ID>?expand=resources&attributes=guest_devices.with_ethernet_type,guest_devices.with_storage_type,hardware.physical_network_ports
-----------------------------------------------------------------------------------------------
