=== Configuration Prerequisites

The XClarity Administrator appliance runs in a virtual machine (VM). Ensure that you meet
the prerequisites that are described in this section before you attempt to install Lenovo
XClarity Administrator.

==== NTP server prerequisites
Ensure that there is a Network Time Protocol (NTP) server in your network that can be used
as the NTP server for Lenovo XClarity Administrator. An NTP server is required to ensure
synchronization between the XClarity Administrator and all managed endpoints.

==== Host prerequisites
The XClarity Administrator appliance runs as a VM on the host system. The following
Hypervisors are supported for installing the XClarity Administrator appliance:

*  VMware ESXi 5.1 update 1 or Version 5.5 or later
*  Microsoft Windows Server 2012 or higher with Hyper-V installed

The host system that is running the XClarity Administrator appliance VM has the following
minimum requirements:

* Two 4-core Intel Xeon processors.
* 6 GB of memory
* A minimum of 64 GB of storage for use by XClarity Administrator

==== Before you begin

* Ensure that you have reviewed the prerequisites for the Lenovo XClarity Administrator virtual appliance (see Supported host systems).
* Ensure that the devices that you intend to manage using Lenovo XClarity Administrator are supported.
* Ensure that firmware for all devices that you intend to manage using Lenovo XClarity Administrator are at the required levels.
* You can download the Lenovo XClarity Administrator virtual-appliance image from the Lenovo XClarity Administrator download webpage to a client workstation. Log on to the Web site, and then use the access key that was given to you to download the image.
