=== Install and Configure Lenovo XClarity Administrator

The Lenovo XClarity Administrator Provider leverages one or more Lenovo XClarity Administrator appliances to centralize resource-management solution and enhance the availability of Lenovo® server systems and solutions. 

Lenovo XClarity Administrator is available stand-alone or as a bundled offering that is known as Lenovo XClarity Pro. Lenovo XClarity Pro is composed of the base Administrator product plus two Lenovo XClarity Integrator modules that provide integration into Microsoft Systems Center or VMware vCenter. Together, these tools provide discovery, monitoring, configuration, and management functions to reduce the cost and complexity of routine system administration for supported devices.

For more information downloading the Lenovo XClarity Appliance or obtaining a license for Lenovo XClarity Pro reference the following link:

* Lenovo XClarity Administrator 
(https://www3.lenovo.com/us/en/data-center/software/systems-management/xclarity)

==== Installation

Lenovo XClarity Administrator is delivered as a virtual appliance that supports industry leading virtualization plaforms (ESXi, Hyper-V, Nutanix). Follow the instructions for importing a virtual machine as provided by your platform.  


==== Configuration

When you access Lenovo XClarity Administrator for the first time, there are several steps that you must complete to initially set up Lenovo XClarity Administrator. Complete the following steps to initially configure XClarity Administrator:


===== Procedure

. Open a web browser.
. Access the web interface is through a secure (https) connection. Enter the following URL
to access XClarity Administrator: https://<IPv4_address>/ui/login.html
. Read and accept the license agreement.
. Create user accounts that have supervisor authority.
. For more information about user accounts, see Managing user accounts.
. Tip: Consider creating at least two user accounts with supervisor authority so that you have a backup, if needed.
. Configure network access, including IP addresses for the data and management networks.
. Configure the date and time.
. Configure security settings, including authentication server, user groups, server certificates, and cryptography mode.
. Manage your chassis and servers.
. Set up automatic notifications to Lenovo Support.

==== Discovering and Managing Hardware

XClarity Administrator can discover manageable systems that are in your environment by
performing an SLP discovery for systems that are on the same IP subnet as
XClarity Administrator. A specified IP address or range of IP addresses also can be used and
information can be imported from a spreadsheet, a process that is known as a Bulk Import.  Discovery options can be accessed by selecting Hardware -> Discover and Manage New Devices from the menu bar.  Discovered systems can now be managed by XClarity Administrator. During this process you will be asked for login credentials for the management module of the target systems and given the option to create a recovery account for the appliances. Managed systems can be monitored, configured and updated via XClarity and the Lenovo XClarity Provider for CloudForms can surface details via the CloudForms user interface.

For additional detail about deploying and configuring XClarity Administrator reference the available support documentation at: https://www3.lenovo.com/us/en/data-center/software/systems-management/xclarity



