=== Discovering and managing hardware using XClarity Administrator

XClarity Administrator can discover manageable devices in your environment by performing an SLP discovery for devices that are on the same IP subnet as XClarity Administrator. A specified IP address or range of IP addresses also can be used, or information can be imported from a spreadsheet, a process that is known as a _bulk import_. Discovery options can be accessed by clicking *Hardware > Discover and Manage New Devices* from the menu bar. Discovered devices can then be managed by XClarity Administrator. During the management process, you are asked for login credentials for the management controller of the target servers and given the option to create a recovery account for the servers. For more information about discovering and managing devices, see the http://sysmgt.lenovofiles.com/help/index.jsp?topic=%2Fcom.lenovo.lxca.doc%2Faug_product_page.html[XClarity Administrator online documentation].

*Note:*

* Ensure that the devices that you intend to manage are supported by XClarity Administrator. For information about supported devices, see http://sysmgt.lenovofiles.com/help/topic/com.lenovo.lxca.doc/plan_supportedhw.html?cp=1_3_1_1[Supported devices] in the XClarity Administrator online documentation.
* Ensure that firmware for all devices that you intend to manage using XClarity Administrator are at the required levels. For more information about supported firmware levels, see http://sysmgt.lenovofiles.com/help/topic/com.lenovo.lxca.doc/plan_supportedfw.html?cp=1_3_1_2[Supported firmware] in the XClarity Administrator online documentation.
