=== Setting up Lenovo XClarity Administrator

Physical-infrastructure providers are used to connect CloudForms to one or more Lenovo XClarity Administrator instances. Lenovo XClarity Administrator is a centralized, resource-management solution that simplifies infrastructure management, speeds responses, and enhances the availability of Lenovo® server systems and solutions. It runs as a virtual appliance that automates discovery, inventory, tracking, monitoring, and provisioning for server, network, and storage hardware in a secure environment.

Lenovo XClarity Administrator supports industry leading virtualization platforms, such as Red Hat with Kernel-based Virtual Machine (KVM), VMware ESXi, Microsoft Hyper-V, Nutanix Acropolis Hypervisor. For a list of supported hypervisors and for hardware and software requirements, see http://sysmgt.lenovofiles.com/help/topic/com.lenovo.lxca.doc/plan_lxcaprerequisites.html?cp=1_3_1_0[Supported host systems] in the Lenovo XClarity Administrator online documentation.

For information about downloading and setting up Lenovo XClarity Administrator, see http://ralfss30.labs.lenovo.com:8200/help/topic/com.lenovo.lxca.doc/setup.html?cp=1_6[Installing and setting up Lenovo XClarity Administrator] in the Lenovo XClarity Administrator online documentation.

*Note:* You can use all available features in Lenovo XClarity Administrator for free for up to 90 days. After 90 days, you can continue to use Lenovo XClarity Administrator to manage and monitor your hardware for free; however, you must purchase a full-function-enablement license to continue using Lenovo XClarity Administrator to configure your hardware using Configuration Patterns and to deploy operating systems. Lenovo XClarity Pro provides entitlement to service and support and the full-function-enablement license for Lenovo XClarity Administrator. For more information about purchasing Lenovo XClarity Pro, contact your Lenovo representative or authorized business partner.
