=== Lenovo XClarity Administrator Provider for RedHat CloudForms Management Engine

The Lenovo XClarity Provider enables IT administrators the ability to integrate the management features of Lenovo XClarity Administrator with the hybrid-cloud management capabilities of RedHat CloudForms Management engine. Lenovo expands physical infrastruction management for on premise cloud configurations by leveraging Lenovo System x hardware management. It provides the  configuration, monitoring, event management, and power monitoring needed to reduce cost and complexity through server consolidation and simplified management. 

Key features include:

* Seamless Integration with Lenovo XClarity Administrator, providing a summary view Lenovo infrastructure, visualizing views of managed servers, host systems and conveniently configuring servers with configuration patterns
* Automatically discovers Lenovo servers running virtualization platforms provided by ESXi, ovirt, KVM and RedHat OpenStack 
* Provides a Timeline of server events
* Provision managed servers for use in on-premise cloud deployments.
* Provides a single interface to monitor systems managed by multiple instances of Lenovo XClarity Administrator
* Customizable filters to organize views of managed systems across the data center.
* Manages the current system settings on the host including BMC, uEFI, and boot order settings for each host system.
* Simplifies system management through custom policies and automation  that respond to the health status of the virtualized host and the status of the managed system.
